PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, email_verified INTEGER NOT NULL DEFAULT 0, image TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS session (id TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS account (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at INTEGER, refresh_token_expires_at INTEGER, scope TEXT, password TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS account_user_idx ON account(user_id);
CREATE TABLE IF NOT EXISTS verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER, updated_at INTEGER);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON verification(identifier);
CREATE TABLE IF NOT EXISTS user_preferences (user_id TEXT PRIMARY KEY, interface_language TEXT NOT NULL DEFAULT 'id', writing_language TEXT NOT NULL DEFAULT 'auto', default_mode TEXT NOT NULL DEFAULT 'P01_STANDARD_REWRITE', local_drafts INTEGER NOT NULL DEFAULT 1, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, title TEXT NOT NULL, language TEXT NOT NULL, preferences_json TEXT NOT NULL DEFAULT '{}', revision INTEGER NOT NULL DEFAULT 0, body_json TEXT, body_r2_key TEXT, storage_mode TEXT NOT NULL DEFAULT 'd1', original_version_id TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS documents_owner_updated_idx ON documents(owner_id, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS documents_owner_id_idx ON documents(owner_id, id);
CREATE TABLE IF NOT EXISTS document_versions (id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE, owner_id TEXT NOT NULL, kind TEXT NOT NULL, revision INTEGER NOT NULL, label TEXT, snapshot_r2_key TEXT NOT NULL, snapshot_hash TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS versions_document_created_idx ON document_versions(document_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS versions_owner_created_idx ON document_versions(owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS versions_snapshot_key_idx ON document_versions(snapshot_r2_key);
CREATE TABLE IF NOT EXISTS locked_terms (id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE, owner_id TEXT NOT NULL, term TEXT NOT NULL, created_at INTEGER NOT NULL, UNIQUE(document_id, term));
CREATE INDEX IF NOT EXISTS locks_document_idx ON locked_terms(document_id, id);
CREATE TABLE IF NOT EXISTS transformations (id TEXT PRIMARY KEY, document_id TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE, owner_id TEXT NOT NULL, prompt_id TEXT NOT NULL, prompt_version TEXT NOT NULL, model TEXT NOT NULL, source_revision INTEGER NOT NULL, source_text TEXT NOT NULL, anchor_json TEXT, runtime_json TEXT NOT NULL, output_json TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT NOT NULL, expires_at INTEGER NOT NULL, applied_at INTEGER, created_at INTEGER NOT NULL, UNIQUE(owner_id, idempotency_key));
CREATE INDEX IF NOT EXISTS transforms_document_created_idx ON transformations(document_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS transforms_expiry_payload_idx ON transformations(expires_at, id);
CREATE TABLE IF NOT EXISTS usage_ledger (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, operation TEXT NOT NULL, status TEXT NOT NULL, period_key TEXT NOT NULL, request_id TEXT NOT NULL, provider_request_id TEXT, prompt_id TEXT, source_characters INTEGER, input_tokens INTEGER, output_tokens INTEGER, latency_ms INTEGER, error_code TEXT, created_at INTEGER NOT NULL, completed_at INTEGER, UNIQUE(owner_id, idempotency_key));
CREATE INDEX IF NOT EXISTS usage_owner_period_idx ON usage_ledger(owner_id, period_key, status);
CREATE INDEX IF NOT EXISTS usage_owner_created_idx ON usage_ledger(owner_id, created_at DESC);
CREATE TABLE IF NOT EXISTS maintenance_state (name TEXT PRIMARY KEY, cursor TEXT, updated_at INTEGER NOT NULL);
