import { runtime } from "../runtime";
import { getSnapshot, putImmutableSnapshot } from "../storage/r2";
import { documentText, plainTextDocument, replaceTextInDocument } from "./serialize";
import type { DocumentCreateInput, DocumentDTO, VersionDTO } from "@/lib/contracts";
import { EditorDocumentSchema } from "@/lib/contracts";
import { RequestError } from "../http";
import type { NotebookAppearance } from "@/lib/notebook/appearance";

type DocumentRow = { id: string; title: string; language: "auto" | "id" | "en"; preferences_json: string; revision: number; body_json: string | null; body_r2_key: string | null; original_version_id?: string | null; color?: string | null; icon?: string | null; created_at: number; updated_at: number };
type VersionRow = { id: string; document_id: string; kind: VersionDTO["kind"]; revision: number; label: string | null; snapshot_r2_key: string; created_at: number; prompt_id: string | null; scope_type: string | null };
const now = () => Date.now();
const id = () => crypto.randomUUID();
function checkedContent(value:unknown){try{const content=EditorDocumentSchema.parse(value);if(documentText(content).length>200000)throw new RequestError("PAYLOAD_TOO_LARGE","Document text exceeds 200,000 characters.",413);return content;}catch(error){if(error instanceof RequestError)throw error;throw new RequestError("INVALID_DOCUMENT","Document structure or formatting is invalid.",400);}}
const parseBody = (value: string) => checkedContent(JSON.parse(value));
const snapshot = (value: unknown) => JSON.stringify(value);

async function rowForOwner(documentId: string, ownerId: string): Promise<DocumentRow> { const row = await runtime().DB.prepare("SELECT id,title,language,preferences_json,revision,body_json,body_r2_key,original_version_id,color,icon,created_at,updated_at FROM documents WHERE id=? AND owner_id=?").bind(documentId, ownerId).first<DocumentRow>(); if (!row) throw new RequestError("NOT_FOUND", "Document not found.", 404); return row; }
async function readBody(row: DocumentRow) { if (row.body_json) return parseBody(row.body_json); if (row.body_r2_key) return parseBody(await getSnapshot(row.body_r2_key)); throw new RequestError("DOCUMENT_CORRUPT", "Document body is unavailable.", 409); }
async function dto(row: DocumentRow): Promise<DocumentDTO> { return { id: row.id, title: row.title, language: row.language, preferences: JSON.parse(row.preferences_json || "{}"), revision: row.revision, originalVersionId: row.original_version_id ?? null, color: row.color ?? null, icon: row.icon ?? null, content: await readBody(row), createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() }; }

export async function createDocument(ownerId: string, input: DocumentCreateInput): Promise<DocumentDTO> {
  const documentId = id(); const versionId = id(); const created = now(); const content = checkedContent(input.content ?? plainTextDocument("")); const body = snapshot(content); const object = await putImmutableSnapshot(documentId, versionId, body);
  await runtime().DB.batch([
    runtime().DB.prepare("INSERT INTO documents (id,owner_id,title,language,preferences_json,revision,body_json,storage_mode,original_version_id,color,icon,created_at,updated_at) VALUES (?,?,?,?,?,0,?,'d1',?,?,?,?,?)").bind(documentId, ownerId, input.title, input.language, JSON.stringify(input.preferences ?? {}), body, versionId, input.color ?? null, input.icon ?? null, created, created),
    runtime().DB.prepare("INSERT INTO document_versions (id,document_id,owner_id,kind,revision,label,snapshot_r2_key,snapshot_hash,created_at) VALUES (?,?,?,'original',0,'Original',?,?,?)").bind(versionId, documentId, ownerId, object.key, object.hash, created)
  ]);
  return { id: documentId, title: input.title, language: input.language, preferences: input.preferences ?? {}, revision: 0, color: input.color ?? null, icon: input.icon ?? null, content, createdAt: new Date(created).toISOString(), updatedAt: new Date(created).toISOString() };
}

export async function getDocument(ownerId: string, documentId: string) { return dto(await rowForOwner(documentId, ownerId)); }
export async function listDocuments(ownerId: string, cursor?: string, limit = 20) {
  const bounded = Number.isFinite(limit) ? Math.min(Math.max(Math.trunc(limit), 1), 50) : 20; const args: unknown[] = [ownerId]; let where = "owner_id=?";
  if (cursor) { const [updatedAt, cursorId] = cursor.split(":"); if (!updatedAt || !cursorId || !/^\d+$/.test(updatedAt)) throw new RequestError("INVALID_CURSOR", "Cursor is invalid."); where += " AND (updated_at < ? OR (updated_at = ? AND id < ?))"; args.push(Number(updatedAt), Number(updatedAt), cursorId); }
  args.push(bounded + 1); const rows = await runtime().DB.prepare(`SELECT id,title,language,revision,color,icon,created_at,updated_at,json_extract(preferences_json,'$.mode') AS mode FROM documents WHERE ${where} ORDER BY updated_at DESC,id DESC LIMIT ?`).bind(...args).all<Omit<DocumentRow, "body_json" | "body_r2_key" | "preferences_json"> & { mode: string | null }>(); const results = rows.results ?? []; const page = results.slice(0, bounded); const last = page.at(-1); return { items: page.map((row) => ({ id: row.id, title: row.title, language: row.language, revision: row.revision, mode: typeof row.mode === "string" ? row.mode : null, color: row.color ?? null, icon: row.icon ?? null, createdAt: new Date(row.created_at).toISOString(), updatedAt: new Date(row.updated_at).toISOString() })), nextCursor: results.length > bounded && last ? `${last.updated_at}:${last.id}` : null };
}

export async function saveDocument(ownerId: string, documentId: string, expectedRevision: number, changes: { content?: unknown; title?: string }, kind: VersionDTO["kind"] = "checkpoint", label: string | null = null, options?: { previewId: string; expectedLockIds?: string[]; promptId?: string; scopeType?: "selection" | "document" }) {
  const existing = await rowForOwner(documentId, ownerId); if (existing.revision !== expectedRevision) throw new RequestError("REVISION_CONFLICT", "The document changed elsewhere. Reload or resolve before saving.", 409, { currentRevision: existing.revision });
  const content = changes.content ? checkedContent(changes.content) : await readBody(existing); const title = changes.title ?? existing.title; const revision = expectedRevision + 1; const versionId = id(); const serialized = snapshot(content); const object = await putImmutableSnapshot(documentId, versionId, serialized); const changed = now();
  const prior = options ? await runtime().DB.prepare("SELECT id FROM document_versions WHERE document_id=? AND owner_id=? AND revision=? LIMIT 1").bind(documentId, ownerId, expectedRevision).first<{ id: string }>() : null;
  const priorId = options && !prior ? id() : null; const priorBody = priorId ? snapshot(await readBody(existing)) : null; const priorObject = priorId && priorBody ? await putImmutableSnapshot(documentId, priorId, priorBody) : null;
  const lockGuard = options?.expectedLockIds === undefined ? "" : " AND (SELECT COUNT(*) FROM locked_terms WHERE document_id=? AND owner_id=?)=? AND NOT EXISTS (SELECT 1 FROM locked_terms WHERE document_id=? AND owner_id=? AND id NOT IN (SELECT value FROM json_each(?)))";
  const update = options ? runtime().DB.prepare(`UPDATE documents SET title=?,body_json=?,body_r2_key=NULL,storage_mode='d1',revision=?,updated_at=? WHERE id=? AND owner_id=? AND revision=? AND EXISTS (SELECT 1 FROM transformations WHERE id=? AND owner_id=? AND document_id=? AND status='preview' AND applied_at IS NULL AND expires_at>?)${lockGuard}`).bind(title, serialized, revision, changed, documentId, ownerId, expectedRevision, options.previewId, ownerId, documentId, changed, ...(options.expectedLockIds === undefined ? [] : [documentId, ownerId, options.expectedLockIds.length, documentId, ownerId, JSON.stringify(options.expectedLockIds)])) : runtime().DB.prepare("UPDATE documents SET title=?,body_json=?,body_r2_key=NULL,storage_mode='d1',revision=?,updated_at=? WHERE id=? AND owner_id=? AND revision=?").bind(title, serialized, revision, changed, documentId, ownerId, expectedRevision);
  const statements = [update];
  if (priorId && priorObject) statements.push(runtime().DB.prepare("INSERT INTO document_versions (id,document_id,owner_id,kind,revision,label,snapshot_r2_key,snapshot_hash,created_at) SELECT ?,?,?, 'checkpoint',?,'Before AI apply',?,?,? WHERE changes()=1").bind(priorId, documentId, ownerId, expectedRevision, priorObject.key, priorObject.hash, changed));
  statements.push(runtime().DB.prepare("INSERT INTO document_versions (id,document_id,owner_id,kind,revision,label,snapshot_r2_key,snapshot_hash,created_at,prompt_id,scope_type) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE changes()=1").bind(versionId, documentId, ownerId, kind, revision, label, object.key, object.hash, changed, options?.promptId ?? null, options?.scopeType ?? null));
  if (options) statements.push(runtime().DB.prepare("UPDATE transformations SET status='applied',applied_at=? WHERE id=? AND owner_id=? AND status='preview' AND applied_at IS NULL AND changes()=1").bind(changed, options.previewId, ownerId));
  const results = await runtime().DB.batch(statements);
  const outputIndex = priorId ? 2 : 1; const markerIndex = outputIndex + 1;
  if ((results[0]?.meta.changes ?? 0) !== 1 || (priorId && (results[1]?.meta.changes ?? 0) !== 1) || (results[outputIndex]?.meta.changes ?? 0) !== 1 || (options && (results[markerIndex]?.meta.changes ?? 0) !== 1)) throw new RequestError("REVISION_CONFLICT", "The document changed elsewhere. Reload or resolve before saving.", 409);
  return { id: documentId, title, language: existing.language, revision, content, createdAt: new Date(existing.created_at).toISOString(), updatedAt: new Date(changed).toISOString() } satisfies DocumentDTO;
}

export async function autosaveDocument(ownerId: string, documentId: string, expectedRevision: number, content: unknown, metadata?: { title?: string; language?: "auto" | "id" | "en"; preferences?: Record<string, unknown> }) { const parsed = checkedContent(content); const current = await rowForOwner(documentId, ownerId); const saved = now(); const result = await runtime().DB.prepare("UPDATE documents SET title=?,language=?,preferences_json=?,body_json=?,body_r2_key=NULL,storage_mode='d1',revision=revision+1,updated_at=? WHERE id=? AND owner_id=? AND revision=?").bind(metadata?.title ?? current.title, metadata?.language ?? current.language, JSON.stringify(metadata?.preferences ?? JSON.parse(current.preferences_json || "{}")), snapshot(parsed), saved, documentId, ownerId, expectedRevision).run(); if ((result.meta.changes ?? 0) !== 1) { const latest = await rowForOwner(documentId, ownerId); throw new RequestError("REVISION_CONFLICT", "The document changed elsewhere. Reload or resolve before saving.", 409, { currentRevision: latest.revision }); } return getDocument(ownerId, documentId); }
// Cosmetic metadata only: no revision bump, no version, updated_at untouched.
export async function updateAppearance(ownerId: string, documentId: string, appearance: NotebookAppearance) { const result = await runtime().DB.prepare("UPDATE documents SET color=?,icon=? WHERE id=? AND owner_id=?").bind(appearance.color, appearance.icon, documentId, ownerId).run(); if ((result.meta.changes ?? 0) !== 1) throw new RequestError("NOT_FOUND", "Document not found.", 404); return { id: documentId, color: appearance.color, icon: appearance.icon }; }
export async function listVersions(ownerId: string, documentId: string, cursor?: string, limit = 20) { await rowForOwner(documentId, ownerId); const bounded = Math.min(Math.max(limit, 1), 50); let sql = "SELECT id,document_id,kind,revision,label,snapshot_r2_key,created_at,prompt_id,scope_type FROM document_versions WHERE document_id=? AND owner_id=?"; const args: unknown[] = [documentId, ownerId]; if (cursor) { const [created, versionId] = cursor.split(":"); if (!created || !versionId || !/^\d+$/.test(created)) throw new RequestError("INVALID_CURSOR", "Cursor is invalid."); sql += " AND (created_at < ? OR (created_at = ? AND id < ?))"; args.push(Number(created), Number(created), versionId); } sql += " ORDER BY created_at DESC,id DESC LIMIT ?"; args.push(bounded + 1); const rows = await runtime().DB.prepare(sql).bind(...args).all<VersionRow>(); const results = rows.results ?? []; const page = results.slice(0, bounded); const last = page.at(-1); return { items: page.map((row) => ({ id: row.id, documentId: row.document_id, kind: row.kind, revision: row.revision, label: row.label, promptId: row.prompt_id, scopeType: row.scope_type, createdAt: new Date(row.created_at).toISOString() })), nextCursor: results.length > bounded && last ? `${last.created_at}:${last.id}` : null }; }
export async function getVersion(ownerId: string, documentId: string, versionId: string) { const row = await runtime().DB.prepare("SELECT id,document_id,kind,revision,label,snapshot_r2_key,created_at FROM document_versions WHERE id=? AND document_id=? AND owner_id=?").bind(versionId, documentId, ownerId).first<VersionRow>(); if (!row) throw new RequestError("NOT_FOUND", "Version not found.", 404); return { id: row.id, documentId: row.document_id, kind: row.kind, revision: row.revision, label: row.label, content: parseBody(await getSnapshot(row.snapshot_r2_key)), createdAt: new Date(row.created_at).toISOString() }; }
export async function updateVersionLabel(ownerId: string, documentId: string, versionId: string, label: string) { const result = await runtime().DB.prepare("UPDATE document_versions SET label=? WHERE id=? AND document_id=? AND owner_id=?").bind(label, versionId, documentId, ownerId).run(); if ((result.meta.changes ?? 0) !== 1) throw new RequestError("NOT_FOUND", "Version not found.", 404); return getVersion(ownerId, documentId, versionId); }
export async function createCheckpoint(ownerId: string, documentId: string, expectedRevision: number, label: string | null) { const existing = await rowForOwner(documentId, ownerId); return saveDocument(ownerId, documentId, expectedRevision, { content: await readBody(existing) }, "checkpoint", label ?? "Manual checkpoint"); }
export async function restoreVersion(ownerId: string, documentId: string, versionId: string, expectedRevision: number) { const version = await runtime().DB.prepare("SELECT id,snapshot_r2_key FROM document_versions WHERE id=? AND document_id=? AND owner_id=?").bind(versionId, documentId, ownerId).first<{ id: string; snapshot_r2_key: string }>(); if (!version) throw new RequestError("NOT_FOUND", "Version not found.", 404); const current = await rowForOwner(documentId, ownerId); const latest = await runtime().DB.prepare("SELECT revision FROM document_versions WHERE document_id=? AND owner_id=? ORDER BY revision DESC LIMIT 1").bind(documentId, ownerId).first<{ revision: number }>(); if ((latest?.revision ?? -1) !== expectedRevision) { await saveDocument(ownerId, documentId, expectedRevision, { content: await readBody(current) }, "checkpoint", "Before restore"); expectedRevision += 1; } return saveDocument(ownerId, documentId, expectedRevision, { content: parseBody(await getSnapshot(version.snapshot_r2_key)) }, "restore", "Restored version"); }
export async function compareVersions(ownerId: string, documentId: string, a: string, b: string) { const rows = await runtime().DB.prepare("SELECT id,snapshot_r2_key FROM document_versions WHERE document_id=? AND owner_id=? AND id IN (?,?)").bind(documentId, ownerId, a, b).all<{ id: string; snapshot_r2_key: string }>(); if ((rows.results?.length ?? 0) !== 2) throw new RequestError("NOT_FOUND", "One or both versions were not found.", 404); const map = new Map((rows.results ?? []).map((row) => [row.id, row.snapshot_r2_key])); return { a: { id: a, content: parseBody(await getSnapshot(map.get(a)!)) }, b: { id: b, content: parseBody(await getSnapshot(map.get(b)!)) } }; }
export async function currentText(ownerId: string, documentId: string) { const value = await getDocument(ownerId, documentId); return { document: value, text: documentText(value.content) }; }
// D1 counts cascaded rows in meta.changes, so any positive count means the owned row was deleted.
export async function deleteDocument(ownerId: string, documentId: string) { const rows = await runtime().DB.prepare("SELECT snapshot_r2_key FROM document_versions WHERE document_id=? AND owner_id=?").bind(documentId, ownerId).all<{ snapshot_r2_key: string }>(); const result = await runtime().DB.prepare("DELETE FROM documents WHERE id=? AND owner_id=?").bind(documentId, ownerId).run(); if ((result.meta.changes ?? 0) < 1) throw new RequestError("NOT_FOUND", "Document not found.", 404); await Promise.all((rows.results ?? []).map((row) => runtime().DOCUMENTS.delete(row.snapshot_r2_key))); }
export { replaceTextInDocument, plainTextDocument };
